import type { ComponentType } from 'react'

/** Settings that every scene has, so generic UI (background, URL) can be shared. */
export interface BaseSceneSettings {
  url: string
  bgColor: string
}

export interface MacbookSettings extends BaseSceneSettings {
  /** Lid angle target — the laptop floats and tilts while open. */
  open: boolean
}

export interface IPhoneSettings extends BaseSceneSettings {
  /** Display on/off. Off shows the dark glass, which is nice for showing off the body. */
  screenOn: boolean
  /** Hex of the titanium frame / glass back. */
  bodyColor: string
  orientation: 'portrait' | 'landscape'
}

export type SceneSettings = MacbookSettings | IPhoneSettings

export interface SceneSettingsMap {
  macbook: MacbookSettings
  iphone: IPhoneSettings
}

export type SceneId = keyof SceneSettingsMap

/** Props handed to both the 3D viewport and every settings panel of a scene. */
export interface SceneViewProps<S extends SceneSettings = SceneSettings> {
  settings: S
  update: (patch: Partial<S>) => void
}

export interface SceneTab<S extends SceneSettings = SceneSettings> {
  id: string
  label: string
  Icon: ComponentType
  Panel: ComponentType<SceneViewProps<S>>
}

export interface SceneConfig<S extends SceneSettings = SceneSettings> {
  id: SceneId
  label: string
  /** One-liner shown under the name in the scene picker. */
  blurb: string
  /** Still of the scene, used as the picker tile. Generated by scripts/capture-thumbs.mjs. */
  thumbnail: string
  /** Initial camera. The Canvas is remounted per scene, so this is applied on switch. */
  camera: { position: [number, number, number]; fov: number }
  defaults: S
  /** Reads deep-link overrides (`?url=…&bg=…`) on top of the defaults. */
  fromParams: (params: URLSearchParams, defaults: S) => S
  Viewport: ComponentType<SceneViewProps<S>>
  tabs: SceneTab<S>[]
}

/**
 * Authoring helper. Each scene is written against its own concrete settings type,
 * but the registry has to hold them side by side — and `SceneConfig<MacbookSettings>`
 * isn't assignable to `SceneConfig<SceneSettings>` because component props are
 * contravariant. This is the one place that seam is crossed; App only ever pairs a
 * config with the settings object stored under the same scene id.
 */
export function defineScene<S extends SceneSettings>(config: SceneConfig<S>): SceneConfig {
  return config as unknown as SceneConfig
}
