import type { ComponentType } from 'react'

/** Settings that every scene has, so generic UI (the backdrop picker) can be shared. */
export interface BaseSceneSettings {
  bgColor: string
}

export interface MacbookSettings extends BaseSceneSettings {
  url: string
  /** Lid angle target — the laptop floats and tilts while open. */
  open: boolean
}

export interface IPhoneSettings extends BaseSceneSettings {
  url: string
  /** Display on/off. Off shows the dark glass, which is nice for showing off the body. */
  screenOn: boolean
  /** Hex of the titanium frame / glass back. */
  bodyColor: string
  orientation: 'portrait' | 'landscape'
}

export interface MobileGridSettings extends BaseSceneSettings {
  /** One entry per site; tiles cycle through the list. Always at least one. */
  urls: string[]
  columns: number
  /** Tiles in each column before the strip wraps around. */
  rows: number
  /** Space between phones, as a fraction of one phone's width. */
  gap: number
  /** Rotation of the whole wall, in degrees. */
  rotation: number
  /** Idle travel, in screen-heights per second. 0 leaves the wall still until scrolled. */
  speed: number
  /** Draw a phone body behind every screen. */
  frame: boolean
  /** Pan every embedded page down its own length and back, all at one speed. */
  pageScroll: boolean
}

export type SceneSettings = MacbookSettings | IPhoneSettings | MobileGridSettings

export interface SceneSettingsMap {
  macbook: MacbookSettings
  iphone: IPhoneSettings
  'mobile-grid': MobileGridSettings
}

export type SceneId = keyof SceneSettingsMap

/** Props handed to both the 3D viewport and every settings panel of a scene. */
export interface SceneViewProps<S extends SceneSettings = SceneSettings> {
  settings: S
  update: (patch: Partial<S>) => void
}

export interface SceneTab<S extends SceneSettings = SceneSettings> {
  id: string
  label: string
  Icon: ComponentType
  Panel: ComponentType<SceneViewProps<S>>
}

export interface SceneConfig<S extends SceneSettings = SceneSettings> {
  id: SceneId
  label: string
  /** One-liner shown under the name in the scene picker. */
  blurb: string
  /** Still of the scene, used as the picker tile. Generated by scripts/capture-thumbs.mjs. */
  thumbnail: string
  /** Initial camera. The Canvas is remounted per scene, so this is applied on switch. */
  camera: { position: [number, number, number]; fov: number }
  defaults: S
  /** Reads deep-link overrides (`?url=…&bg=…`) on top of the defaults. */
  fromParams: (params: URLSearchParams, defaults: S) => S
  Viewport: ComponentType<SceneViewProps<S>>
  tabs: SceneTab<S>[]
}

/**
 * Authoring helper. Each scene is written against its own concrete settings type,
 * but the registry has to hold them side by side — and `SceneConfig<MacbookSettings>`
 * isn't assignable to `SceneConfig<SceneSettings>` because component props are
 * contravariant. This is the one place that seam is crossed; App only ever pairs a
 * config with the settings object stored under the same scene id.
 */
export function defineScene<S extends SceneSettings>(config: SceneConfig<S>): SceneConfig {
  return config as unknown as SceneConfig
}
